### ISSUE TITLE
Paper and code mismatch

### ISSUE THREAD

**Issue by DenisDiachkov** [ShinyWang33/eSL-Net#1]
Hello, 

I got a bit confused by this line.
https://github.com/ShinyWang33/eSL-Net/blob/d30c5ec294e8d1a881dc6415e2d44c483d0bc583/code/model_n2.py#L69
In the paper it is ReLU, not Sigmoid.

![image](https://user-images.githubusercontent.com/32463752/92575630-3a44f980-f291-11ea-84be-775c3d8720da.png)

Is it a paper typo or a code bug?

**Comment by ShinyWang33** [comment]
Sorry. It‘s a paper typo. All results are based on the model code.

**Comment by DenisDiachkov** [comment]
Ok, thank you!
