### ISSUE TITLE
question about your validation set

### ISSUE THREAD

**Issue by HaoDot** [ShinyWang33/eSL-Net#3]
Hi nice work!
According your link for val set, it's **REDS**,rather than gopro. I don't know whether you put a wrong link or you did validate your model in **REDS** val set.
I am sincerely waiting for your reply, thanks!

**Comment by ShinyWang33** [comment]
It's a right link. Because REDS dataset is captured by Gopro camera, and the dataset is named gopro dataset in many papers in the same field.

**Comment by HaoDot** [comment]
Got it! Thx for your reply!
